### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by vegu** [fullctl/aaactl#6]
Tests currently hard fail without running at all

https://github.com/fullctl/aaactl/pull/5/checks?check_run_id=1824862234

**Comment by egfrank** [comment]
Hi @vegu , this is being caused by not configuring the test settings correctly for it to run in Github workflow and there are additional questions of if we want the Workflow to launch a Docker container or to run the tests outside the container.

I think when we get a chance we should just talk on Slack about this because there are just a few decisions we need to make

**Comment by egfrank** [comment]
Working on getting the github action to launch a container to run tests, I modified the `run_tests` command to also call coverage.

On this run https://github.com/fullctl/aaactl/actions/runs/550081165

I got a bizarre error when trying to `pip install poetry`. Apparently caused by an update to the package `cryptography` which literally happened today: https://github.com/pyca/cryptography/issues/5771

**Comment by egfrank** [comment]
Here's a reference to this failing in the poetry issues specifically:

https://github.com/python-poetry/poetry/issues/3661

**Comment by egfrank** [comment]
This is unfortunately still an issue:

Hi so I'm currently seeing that with ixctl and fullctl the way we're installing poetry in the container is now broken:
  
      =============================DEBUG ASSISTANCE=============================
      If you are seeing a compilation error please try the following steps to
      successfully install cryptography:
      1) Upgrade to the latest pip and try again. This will fix errors for most
         users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
      2) Read https://cryptography.io/en/latest/installation.html for specific
         instructions for your platform.
      3) Check our frequently asked questions for more information:
         https://cryptography.io/en/latest/faq.html
      4) Ensure you have a recent Rust toolchain installed:
         https://cryptography.io/en/latest/installation.html#rust
      5) If you are experiencing issues with Rust for *this release only* you may
         set the environment variable `CRYPTOGRAPHY_DONT_BUILD_RUST=1`.
      =============================DEBUG ASSISTANCE=============================
  error: Can not find Rust compiler
  ----------------------------------------
  ERROR: Failed building wheel for cryptography
Successfully built msgpack
Failed to build cryptography
ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
ERROR: Service 'django' failed to build : The command '/bin/sh -c pip install "poetry==$POETRY_VERSION"' returned a non-zero code: 1
There's basically a scenario where the new version of cryptography, which is a dependency of poetry , requires Rust, which isn't installed into the Alpine containers. Additionally, you can't even add rust  to apk add bc it needs to install a higher version of rust than apk installs by default. (edited) 
9:27
You can see in this Github action run : https://github.com/fullctl/aaactl/runs/1860188738?check_suite_focus=true  that the Docker build is failing on RUN pip install "poetry==$POETRY_VERSION"  . This can actually be resolved either through installing Poetry via Curl, or using Pip to download Cryptography before poetry
9:28
But then weirdly when I was installing the packages for fullctl , it tried to install cryptography again and failed that time

**Comment by egfrank** [comment]
I think this is okay to close (?)

**Comment by vegu** [comment]
Yes, closing
